apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesseract-server
  namespace: tesseract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesseract-server
  template:
    metadata:
      labels:
        app: tesseract-server
    spec:
      serviceAccountName: tesseract-sa
      containers:
      - name: tesseract
        image: ko://github.com/transparency-dev/tesseract/cmd/tesseract/gcp
        args:
        - "--bucket=tesseract-storage-${PROJECT_ID}"
        - "--spanner_db_path=projects/${PROJECT_ID}/instances/tesseract-instance/databases/tesseract-db"
        - "--signer_public_key_secret_name=${PUB_KEY_SECRET_NAME}"
        - "--signer_private_key_secret_name=${PRIV_KEY_SECRET_NAME}"
        - "--http_endpoint=0.0.0.0:80"
        - "--origin=tesseract-benchmark"
        - "--path_prefix=tesseract-benchmark"
        - "--roots_pem_file=/config/roots.pem"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: tesseract-config
---
apiVersion: v1
kind: Service
metadata:
  name: tesseract-server
  namespace: tesseract
spec:
  selector:
    app: tesseract-server
  ports:
  - name: http
    port: 80
  type: LoadBalancer